apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
  selector:
    service: postgres
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:alpine
        resources:
          requests:
            cpu: 0.1
            memory: 100Mi
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: uniq
        - name: POSTGRES_PASSWORD
          value: uniq
        - name: POSTGRES_DB
          value: uniq
